Blog/urls.py
from django.urls import path, include
from .views import BlogList, BlogDetailView, add_blog_comment

app_name = 'Blog'
urlpatterns = [
    path('', BlogList.as_view(), name='blog_list'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('add-article-comment', add_blog_comment, name='add_blog_comment'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index')
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=5000)
    image = models.ImageField(max_length=1000, upload_to='static_cdn/media')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('Blog:blog_detail', args=[self.id])

    def __str__(self):
        return self.title

    def get_active_blogs(self):
        return Blog.objects.filter(active=True)

Comments/models.py
from django.db import models
from Blog.models import Blog


class Comment(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=500)
    text = models.TextField(max_length=5000)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    parent = models.ForeignKey('Comment', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
        # return f"{self.id}, {self.blog.title}"

Blog/views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from django.views.generic import ListView, DetailView
from Comments.models import Comment
from Comments.forms import CommentForm, CommentFormNew
from django.contrib import messages


# def blog_list(request):
#     blogs = Blog.objects.filter(active=True)
#     context = {
#         'blogs': blogs
#     }
#     return render(request, 'Blog/Blog.html', context=context)

class BlogList(ListView):
    # model = Blog
    queryset = Blog.objects.filter(active=True)
    template_name = "Blog/Blog.html"
    paginate_by = 3
    context_object_name = 'blogs'


# def blog_detail(request, blog_id):
#     comment_form = CommentForm()
#     detail_blog = get_object_or_404(Blog, id=blog_id, active=True)
#     comments = detail_blog.comment_set.filter(active=True)
#
#     if request.method == 'POST':
#         comment_form = CommentForm(request.POST)
#         if comment_form.is_valid():
#             name = comment_form.cleaned_data.get('name')
#             email = comment_form.cleaned_data.get('email')
#             text = comment_form.cleaned_data.get('text')
#             Comment.objects.create(
#                 name=name,
#                 email=email,
#                 text=text,
#                 blog=detail_blog,
#             )
#             messages.add_message(request, messages.SUCCESS, 'Your comment has been successfully registered.')
#             return redirect('Blog:blog_detail', detail_blog.id)
#         messages.add_message(request, messages.ERROR, 'Your comment has not been successfully registered.')
#
#     context = {
#         'blog_detail': detail_blog,
#         'comment_form': comment_form,
#         'comments': comments,
#     }
#     return render(request, 'Blog/Blog_Detail.html', context=context)

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'Blog/Blog_Detail.html'
    # context_object_name = 'blog_detail'

    def get_queryset(self):
        query = super(BlogDetailView, self).get_queryset()
        query = query.filter(active=True)
        return query

    def get_context_data(self, **kwargs):
        # context = super().get_context_data(**kwargs)
        context = super(BlogDetailView, self).get_context_data()
        blog: Blog = kwargs.get('object')
        context['comment_form'] = CommentForm()
        # context['comments'] = self.object.comment_set.filter(active=True, parent=None).prefetch_related(
        #     'comment_set')
        context['comments'] = Comment.objects.filter(blog_id=blog.id, parent=None).order_by(
            '-created').prefetch_related('blog__comment_set')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            name = comment_form.cleaned_data.get('name')
            email = comment_form.cleaned_data.get('email')
            text = comment_form.cleaned_data.get('text')
            Comment.objects.create(
                name=name,
                email=email,
                text=text,
                blog=self.object,
            )
            messages.add_message(request, messages.SUCCESS, 'Your comment has been successfully registered.')
            return redirect('Blog:blog_detail', self.object.id)
        messages.add_message(request, messages.ERROR, 'Your comment has not been successfully registered.')
        context = self.get_context_data()
        context['comment_form'] = comment_form
        return self.render_to_response(context)


def add_blog_comment(request: HttpRequest):
    blog_id = request.GET.get('blog_id')
    blog_comment = request.GET.get('blog_comment')
    parent_id = request.GET.get('parent_id')
    new_comment = Comment(blog_id=blog_id, text=blog_comment, parent_id=parent_id)
    new_comment.save()

Blog/templates/Blog/Blog.html
<!doctype html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap Min CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Animate Min CSS -->
    <link rel="stylesheet" href="/static/css/animate.min.css">
    <!-- Fontawesome Min CSS -->
    <link rel="stylesheet" href="/static/css/fontawesome.min.css">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <!-- Magnific Popup Min CSS -->
    <link rel="stylesheet" href="/static/css/magnific-popup.min.css">
    <!-- Odometer Min CSS -->
    <link rel="stylesheet" href="/static/css/odometer.min.css">
    <!-- Owl Carousel Min CSS -->
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <!-- Style CSS -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/static/css/responsive.css">

    <title>Alysa - Personal Portfolio Template</title>

    <link rel="icon" type="image/png" href="/static/img/favicon.png">
</head>

<body id="home" data-bs-spy="scroll" data-bs-offset="70">

<!-- Start Preloader Area -->
<div class="preloader">
    <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>
<!-- End Preloader Area -->

<!-- Start Navbar Area -->
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-style-two">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}"><img src="/static/img/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {% comment %}<div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="#home">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                <li class="nav-item"><a class="nav-link" href="#portfolio">Works</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#feedback">Feedback</a></li>
                <li class="nav-item"><a class="nav-link" href="#blog">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
            </ul>
        </div>{% endcomment %}
    </div>
</nav>
<!-- End Navbar Area -->

<!-- Start Page Title Area -->
<div class="page-title-area bg-main-color">
    <div class="container">
        <h2>Blog</h2>
    </div>
</div>
<!-- End Page Title Area -->

<!-- Start Blog Area -->
<section id="blog" class="blog-area ptb-120 bg-gray-dark">
    <div class="container">
        <div class="row">
            {% for blog in blogs %}
                <div class="col-lg-4 col-md-6">
                    <div class="single-blog-post white-color">
                        <div class="post-image">
                            <a href="{% url 'Blog:blog_detail' blog.id %}"><img src="{{ blog.image.url }}" alt="{{ blog.title }}"></a>
                        </div>

                        <div class="post-content">
                            <h3><a href="{% url 'Blog:blog_detail' blog.id %}">{{ blog.title }}</a></h3>
                            <p>{{ blog.description|safe|truncatewords:50 }}</p>
                            <a href="{% url 'Blog:blog_detail' blog.id %}" class="read-more-btn">Read More</a>
                        </div>
                    </div>
                </div>
            {% endfor %}


            <div class="col-lg-12 col-md-12">
                <div class="pagination-area">
                    {% comment %}<a href="#" class="prev page-numbers"><i class="fas fa-angle-double-left"></i></a>{% endcomment %}
                    {% for page in paginator.page_range %}
                        <a href="?page={{ page }}" class="page-numbers">{{ page }}</a>
                    {% endfor %}
                    {% comment %}<span class="page-numbers current" aria-current="page">2</span>
                    <a href="#" class="page-numbers">3</a>
                    <a href="#" class="page-numbers">4</a> {% endcomment %}
                    {% comment %}<a href="#" class="next page-numbers"><i class="fas fa-angle-double-right"></i></a>{% endcomment %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Blog Area -->

<!-- Start Copyright Area -->
<div class="copyright-area">
    <div class="container">
        <p><i class="far fa-copyright"></i> Copyright 2021. All Rights are Reserved.</p>
    </div>
</div>
<!-- End Copyright Area -->

<div class="go-top"><i class="fas fa-arrow-up"></i></div>

<!-- jQuery Min JS -->
<script src="/static/js/jquery.min.js"></script>
<!-- Popper Min JS -->
<script src="/static/js/popper.min.js"></script>
<!-- Bootstrap Min JS -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- Mixitup Min JS -->
<script src="/static/js/mixitup.min.js"></script>
<!-- Magnific Popup Min JS -->
<script src="/static/js/jquery.magnific-popup.min.js"></script>
<!-- Owl Carousel Min JS -->
<script src="/static/js/owl.carousel.min.js"></script>
<!-- Appear Min JS -->
<script src="/static/js/jquery.appear.js"></script>
<!-- Odometer Min JS -->
<script src="/static/js/odometer.min.js"></script>
<!-- Tilt JS -->
<script src="/static/js/tilt.jquery.js"></script>
<!-- Particles Min JS -->
<script src="/static/js/particles.min.js"></script>
<!-- Parallax Min JS -->
<script src="/static/js/parallax.min.js"></script>
<!-- WOW Min JS -->
<script src="/static/js/wow.min.js"></script>
<!-- Form Validator Min JS -->
<script src="/static/js/form-validator.min.js"></script>
<!-- Contact Form Min JS -->
<script src="/static/js/contact-form-script.js"></script>
<!-- Main JS -->
<script src="/static/js/main.js"></script>
</body>
</html>

Blog/templates/Blog/Blog_Detail.html
{% load widget_tweaks %}
<!doctype html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap Min CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Animate Min CSS -->
    <link rel="stylesheet" href="/static/css/animate.min.css">
    <!-- Fontawesome Min CSS -->
    <link rel="stylesheet" href="/static/css/fontawesome.min.css">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <!-- Magnific Popup Min CSS -->
    <link rel="stylesheet" href="/static/css/magnific-popup.min.css">
    <!-- Odometer Min CSS -->
    <link rel="stylesheet" href="/static/css/odometer.min.css">
    <!-- Owl Carousel Min CSS -->
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <!-- Style CSS -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/static/css/responsive.css">

    <title>Alysa - Personal Portfolio Template</title>

    <link rel="icon" type="image/png" href="/static/img/favicon.png">
</head>

<body id="home" data-bs-spy="scroll" data-bs-offset="70">

<!-- Start Preloader Area -->
<div class="preloader">
    <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>
<!-- End Preloader Area -->

<!-- Start Navbar Area -->
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-style-two">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}"><img src="/static/img/logo.png" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </div>
</nav>
<!-- End Navbar Area -->

<!-- Start Page Title Area -->
<div class="page-title-area bg-main-color">
    <div class="container">
        <h2>Blog Details</h2>
    </div>
</div>
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>New Message!</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}

{% endif %}
<!-- End Page Title Area -->

<!-- Start Blog Details Area -->
<section class="blog-details-area ptb-120 bg-gray-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 offset-lg-2 offset-md-0">
                <div class="blog-details">
                    <div class="article-image">
                        <img src="{{ blog.image.url }}" alt="image">
                    </div>

                    <div class="article-content">
                        <div class="entry-meta">
                            <ul>
                                <li>
                                    <i class="far fa-user-circle"></i>
                                    By: <a href="#">{{ blog.author }}</a>
                                </li>

                                <li>{{ blog.created }}</li>

                                <li><a href="#">Tech</a></li>

                                {% comment %}<li>2 Mins Read</li>{% endcomment %}

                                {% comment %}<li>521 Views</li>{% endcomment %}

                                <li><a href="#">3 Comments</a></li>
                            </ul>
                        </div>

                        {% comment %}<h3>{{ blog.title }}</h3>{% endcomment %}
                        <blockquote class="wp-block-quote">
                            <p>{{ blog.title }}</p>

                            <cite>{{ blog.author }}</cite>
                        </blockquote>

                        <p>{{ blog.description }}</p>


                    </div>

                    <div class="article-footer">
                        <div class="article-tags">
                            <span><i class="fas fa-bookmark"></i></span>

                            <a href="#">Fashion</a>,
                            <a href="#">Games</a>,
                            <a href="#">Travel</a>
                        </div>

                        <div class="article-share">
                            <ul class="social">
                                <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="comments-area">
                    <h3 class="comments-title">Comments:</h3>

                    <ol class="comment-list" id="comment_form">
                        <li class="comment">
                            {% if comments %}
                                {% for comment in comments %}
                                    <article class="comment-body">
                                        <input type="hidden" id="parent_id">
                                        <footer class="comment-meta">
                                            <div class="comment-author vcard">
                                                <b class="fn">{{ comment.name }}</b>
                                                <span class="says">says:</span>
                                            </div>

                                            <div class="comment-metadata">
                                                <a href="#">
                                                    <time>{{ comment.created }}</time>
                                                </a>
                                            </div>
                                        </footer>

                                        <div class="comment-content">
                                            <p id="commentText">{{ comment.text }}</p>
                                        </div>

                                        {% comment %}<div class="reply">
                                            <a onclick="fillParentId({{ comment.id }})"
                                               class="comment-reply-link">Reply</a>
                                        </div>{% endcomment %}
                                    </article>
                                    {% for sub_comment in comment.comment_set.all %}
                                        <ol class="children" id="comment_form">
                                            <input type="hidden" id="parent_id">
                                            <li class="comment">
                                                <article class="comment-body">
                                                    <footer class="comment-meta">
                                                        <div class="comment-author vcard">
                                                            <b class="fn">{{ sub_comment.name }}</b>
                                                            <span class="says">says:</span>
                                                        </div>

                                                        <div class="comment-metadata">
                                                            <a href="#">
                                                                <time>{{ sub_comment.created }}</time>
                                                            </a>
                                                        </div>
                                                    </footer>

                                                    <div class="comment-content">
                                                        <p>{{ sub_comment.text }}</p>
                                                    </div>

                                                </article>
                                            </li>

                                        </ol>
                                    {% endfor %}


                                {% endfor %}
                            {% else %}
                                <h3>There is no comment for this post yet !</h3>
                            {% endif %}


                        </li>
                    </ol>

                    <div class="comment-respond">
                        <h3 class="comment-reply-title">Leave a Reply</h3>

                        <form class="comment-form" method="post" id="comment_form">
                            <input type="hidden" id="parent_id" value="">
                            {% csrf_token %}
                            <div class="form-group">
                                <p class="comment-form-comment" id="commentText">
                                    {{ comment_form.text.label_tag }}
                                    {{ comment_form.text }}
                                    {{ comment_form.text.errors }}
                                </p>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <p class="comment-form-author">
                                    {{ comment_form.name.label_tag }}
                                    {{ comment_form.name }}
                                    {{ comment_form.name.errors }}
                                </p>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <p class="comment-form-email">
                                    {{ comment_form.email.label_tag }}
                                    {{ comment_form.email }}
                                    {{ comment_form.email.errors }}
                                </p>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                {{ comment_form.captcha.label_tag }}
                                {{ comment_form.captcha }}
                                {{ comment_form.captcha.errors }}

                                <div class="help-block with-errors"></div>
                            </div>
                            <p class="form-submit">
                                <input onclick="sendBlogComment({{ blog.id }})" type="submit" name="submit"
                                       id="submit" class="submit" value="Post Comment">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Blog Details Area -->

<!-- Start Copyright Area -->
<div class="copyright-area">
    <div class="container">
        <p><i class="far fa-copyright"></i> Copyright 2021. All Rights are Reserved.</p>
    </div>
</div>
<!-- End Copyright Area -->

<div class="go-top"><i class="fas fa-arrow-up"></i></div>

<!-- jQuery Min JS -->
<script src="/static/js/jquery.min.js"></script>
<!-- Popper Min JS -->
<script src="/static/js/popper.min.js"></script>
<!-- Bootstrap Min JS -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- Mixitup Min JS -->
<script src="/static/js/mixitup.min.js"></script>
<!-- Magnific Popup Min JS -->
<script src="/static/js/jquery.magnific-popup.min.js"></script>
<!-- Owl Carousel Min JS -->
<script src="/static/js/owl.carousel.min.js"></script>
<!-- Appear Min JS -->
<script src="/static/js/jquery.appear.js"></script>
<!-- Odometer Min JS -->
<script src="/static/js/odometer.min.js"></script>
<!-- Tilt JS -->
<script src="/static/js/tilt.jquery.js"></script>
<!-- Particles Min JS -->
<script src="/static/js/particles.min.js"></script>
<!-- Parallax Min JS -->
<script src="/static/js/parallax.min.js"></script>
<!-- WOW Min JS -->
<script src="/static/js/wow.min.js"></script>
<!-- Form Validator Min JS -->
<script src="/static/js/form-validator.min.js"></script>
<!-- Contact Form Min JS -->
<script src="/static/js/contact-form-script.js"></script>
<!-- Main JS -->
<script src="/static/js/main.js"></script>
<script src="/static/js/custom.js"></script>
</body>
</html>